name: moneygone
description: "A clean and user-friendly Flutter expense tracker powered by Firebase, helping you track, manage, and understand where your money goes."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0

  # Environment variables
  envied: ^1.3.9
  get: ^4.7.3
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter linting
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.15.1
  envied_generator: ^1.3.9

  # App icon generation
  flutter_launcher_icons: ^0.14.4

# --------------------------------------------------
# Flutter Launcher Icons
# --------------------------------------------------

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/appIcon.png" # dart run flutter_launcher_icons

# --------------------------------------------------
# Flutter
# --------------------------------------------------

flutter:
  uses-material-design: true

  assets:
    - assets/images/